-- CreateTable
CREATE TABLE "Player" (
    "id" TEXT NOT NULL,
    "summonerId" TEXT NOT NULL,
    "matchId" TEXT NOT NULL,
    "playerName" TEXT NOT NULL,
    "tagLine" TEXT NOT NULL,
    "regionInfo" TEXT NOT NULL,
    "queueInfo" TEXT NOT NULL,
    "relativeTime" TEXT NOT NULL,
    "gameDuration" TEXT NOT NULL,
    "outcome" TEXT NOT NULL,
    "champIcon" TEXT NOT NULL,
    "champLevel" INTEGER NOT NULL,
    "spellInfo1" TEXT NOT NULL,
    "spellInfo2" TEXT NOT NULL,
    "runeInfo1" TEXT NOT NULL,
    "runeInfo2" TEXT NOT NULL,
    "kills" INTEGER NOT NULL,
    "deaths" INTEGER NOT NULL,
    "assists" INTEGER NOT NULL,
    "kdaRatio" INTEGER NOT NULL,
    "kpRatio" INTEGER,
    "gold" INTEGER NOT NULL,
    "creepScore" INTEGER NOT NULL,
    "creepScorePerMin" INTEGER NOT NULL,
    "controlWards" INTEGER NOT NULL,
    "itemId0" INTEGER NOT NULL,
    "itemId1" INTEGER NOT NULL,
    "itemId2" INTEGER NOT NULL,
    "itemId3" INTEGER NOT NULL,
    "itemId4" INTEGER NOT NULL,
    "itemId5" INTEGER NOT NULL,
    "itemId6" INTEGER NOT NULL,
    "visionPings" INTEGER NOT NULL,
    "pushPings" INTEGER NOT NULL,
    "dangerPings" INTEGER NOT NULL,
    "pathingPings" INTEGER NOT NULL,
    "assistPings" INTEGER NOT NULL,
    "missingPings" INTEGER NOT NULL,
    "multiKill" TEXT,
    "blueTeamPlayers" TEXT[],
    "blueTeamTags" TEXT[],
    "blueTeamChamps" TEXT[],
    "redTeamPlayers" TEXT[],
    "redTeamTags" TEXT[],
    "redTeamChamps" TEXT[],

    CONSTRAINT "Player_pkey" PRIMARY KEY ("id")
);
